apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-manager.yml
- external-dns.yml
- external-secrets.yml
- headlamp.yml
- karpenter.yml
- karpenter-crd.yml
- nginx.yml
- prom-graf.yml