apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: karpenter-nodepool
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["t"]
        - key: karpenter.k8s.aws/instance-generation
          operator: In
          values: ["2", "3"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["micro"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: al2023-latest
      expireAfter: 720h # 30 * 24h = 720h
  limits:
    cpu: 100
    nodes: 5
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: al2023-latest
spec:
  role: "karpenter-node-role"
  amiSelectorTerms:
    - alias: al2023@latest # this needs to be correct otherwise you will get an error that the NodeClaim cannot associate with the Node
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "juned-cluster"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "juned-cluster"