provider: aws

policy: sync # this will create and delete the records within Route 53

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::677276074604:role/external-dns-role

aws:
  region: eu-west-2

domainFilters:
- lab.juned.co.uk # needed otherwise it will have the ability to create records for any domain

nodeSelector:
  infra: "true"
tolerations:
  - key: infra
    operator: Equal
    value: "true"